<a href="https://colab.research.google.com/github/Uche002/My-SQL-PORTFOLIO-PROJECT-1/blob/main/KENNY_CHALLENGE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('EDO.csv')
df

,Timestamp,battery voltage(V),inverter voltage(V),grid voltage(V),inverter current(A),grid current(A),load current(A),PGrid(W),PLoad(W),accumulated buy power(kWh),accumulated sell power(kWh),accumulated load power(kWh),accumulated self_use power(kWh),batt power(W),PV voltage(V),charger current(A),charger power(W),accumulated power(kWh)
0,2021-08-01 23:58:45,51.2,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4576,77,0.0,0.0,0.0,4421
1,2021-08-01 23:54:26,51.2,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4576,76,0.0,0.0,0.0,4421
2,2021-08-01 23:49:34,51.2,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4576,76,0.0,0.0,0.0,4421
3,2021-08-01 23:44:42,51.2,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4576,76,0.0,0.0,0.0,4421
4,2021-08-01 23:39:15,51.2,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4576,76,0.0,0.0,0.0,4421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,2021-08-01 00:22:06,50.9,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4575,76,0.0,0.0,0.0,4418
282,2021-08-01 00:17:13,50.9,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4575,76,0.0,0.0,0.0,4418
283,2021-08-01 00:12:20,50.9,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4575,76,0.0,0.0,0.0,4418
284,2021-08-01 00:07:28,50.9,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4575,76,0.0,0.0,0.0,4418
285,2021-08-01 00:02:03,51.0,219.8,0.0,1.7,0.0,0.3,0,0,95,0,4400,4575,76,0.0,0.0,0.0,4418

In [ ]:
pivot = df.pivot_table(index=['Timestamp'], values=['battery voltage(V)','PLoad(W)','charger power(W)'])

print (pivot)

                     PLoad(W)  battery voltage(V)  charger power(W)
Timestamp
2021-08-01 00:02:03         0                51.0               0.0
2021-08-01 00:07:28         0                50.9               0.0
2021-08-01 00:12:20         0                50.9               0.0
2021-08-01 00:17:13         0                50.9               0.0
2021-08-01 00:22:06         0                50.9               0.0
...                       ...                 ...               ...
2021-08-01 23:39:15         0                51.2               0.0
2021-08-01 23:44:42         0                51.2               0.0
2021-08-01 23:49:34         0                51.2               0.0
2021-08-01 23:54:26         0                51.2               0.0
2021-08-01 23:58:45         0                51.2               0.0

[286 rows x 3 columns]

In [ ]:
df.dtypes

Timestamp                           object
battery voltage(V)                 float64
inverter voltage(V)                float64
grid voltage(V)                    float64
inverter current(A)                float64
grid current(A)                    float64
load current(A)                    float64
PGrid(W)                             int64
PLoad(W)                             int64
accumulated buy power(kWh)           int64
accumulated sell power(kWh)          int64
accumulated load power(kWh)          int64
accumulated self_use power(kWh)      int64
batt power(W)                        int64
PV voltage(V)                      float64
charger current(A)                 float64
charger power(W)                   float64
accumulated power(kWh)               int64
dtype: object

In [ ]:
df['Timestamp'] = pd.to_datetime(df.Timestamp)

In [ ]:
df.dtypes

Timestamp                          datetime64[ns]
battery voltage(V)                        float64
inverter voltage(V)                       float64
grid voltage(V)                           float64
inverter current(A)                       float64
grid current(A)                           float64
load current(A)                           float64
PGrid(W)                                    int64
PLoad(W)                                    int64
accumulated buy power(kWh)                  int64
accumulated sell power(kWh)                 int64
accumulated load power(kWh)                 int64
accumulated self_use power(kWh)             int64
batt power(W)                               int64
PV voltage(V)                             float64
charger current(A)                        float64
charger power(W)                          float64
accumulated power(kWh)                      int64
dtype: object

In [1]:
df.Timestamp.dt.hour

NameError: ignored